In [1]:
import pandas as pd
import json
import re

In [2]:
with open('wikipedia-movies.json', 'r') as file:
    wiki_movies_raw = json.load(file)

In [3]:
len(wiki_movies_raw)

7311

In [4]:
wiki_movies_df = pd.DataFrame(wiki_movies_raw)
wiki_movies_df.head()

url    year  \
0  https://en.wikipedia.org/wiki/The_Adventures_o...  1990.0   
1  https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990.0   
2   https://en.wikipedia.org/wiki/Air_America_(film)  1990.0   
3    https://en.wikipedia.org/wiki/Alice_(1990_film)  1990.0   
4      https://en.wikipedia.org/wiki/Almost_an_Angel  1990.0   

                               imdb_link                            title  \
0  https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane   
1  https://www.imdb.com/title/tt0098994/             After Dark, My Sweet   
2  https://www.imdb.com/title/tt0099005/                      Air America   
3  https://www.imdb.com/title/tt0099012/                            Alice   
4  https://www.imdb.com/title/tt0099018/                  Almost an Angel   

          Directed by                  Produced by  \
0        Renny Harlin   [Steve Perry, Joel Silver]   
1         James Foley  [Ric Kidney, Robert Redlin]   
2  Roger Spottiswoode               Daniel Melnick   
3         Woody Allen              Robert Greenhut   
4        John Cornell                 John Cornell   

                                Screenplay by                     Story by  \
0  [David Arnott, James Cappe, Daniel Waters]  [David Arnott, James Cappe]   
1                [James Foley, Robert Redlin]                          NaN   
2                  [John Eskow, Richard Rush]                          NaN   
3                                         NaN                          NaN   
4                                         NaN                          NaN   

                                            Based on  \
0                        [Characters, by Rex Weiner]   
1  [the novel, After Dark, My Sweet, by, Jim Thom...   
2             [Air America, by, Christopher Robbins]   
3                                                NaN   
4                                                NaN   

                                            Starring  ... Predecessor  \
0  [Andrew Dice Clay, Wayne Newton, Priscilla Pre...  ...         NaN   
1  [Jason Patric, Rachel Ward, Bruce Dern, George...  ...         NaN   
2  [Mel Gibson, Robert Downey Jr., Nancy Travis, ...  ...         NaN   
3  [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  ...         NaN   
4        [Paul Hogan, Elias Koteas, Linda Kozlowski]  ...         NaN   

  Founders Area served Products Services Russian Hebrew Revenue  \
0      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
1      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
2      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
3      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
4      NaN         NaN      NaN      NaN     NaN    NaN     NaN   

  Operating income Polish  
0              NaN    NaN  
1              NaN    NaN  
2              NaN    NaN  
3              NaN    NaN  
4              NaN    NaN  

[5 rows x 193 columns]

In [5]:
wiki_movies_df.columns.to_list()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resti

Now we can pick up which columns we don't want or don't need in the analysis

# Investigating the wikipedia data

### Inspect 

In [6]:
wiki_movies_df = pd.DataFrame(wiki_movies_raw)
wiki_movies_df.head()

url    year  \
0  https://en.wikipedia.org/wiki/The_Adventures_o...  1990.0   
1  https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990.0   
2   https://en.wikipedia.org/wiki/Air_America_(film)  1990.0   
3    https://en.wikipedia.org/wiki/Alice_(1990_film)  1990.0   
4      https://en.wikipedia.org/wiki/Almost_an_Angel  1990.0   

                               imdb_link                            title  \
0  https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane   
1  https://www.imdb.com/title/tt0098994/             After Dark, My Sweet   
2  https://www.imdb.com/title/tt0099005/                      Air America   
3  https://www.imdb.com/title/tt0099012/                            Alice   
4  https://www.imdb.com/title/tt0099018/                  Almost an Angel   

          Directed by                  Produced by  \
0        Renny Harlin   [Steve Perry, Joel Silver]   
1         James Foley  [Ric Kidney, Robert Redlin]   
2  Roger Spottiswoode               Daniel Melnick   
3         Woody Allen              Robert Greenhut   
4        John Cornell                 John Cornell   

                                Screenplay by                     Story by  \
0  [David Arnott, James Cappe, Daniel Waters]  [David Arnott, James Cappe]   
1                [James Foley, Robert Redlin]                          NaN   
2                  [John Eskow, Richard Rush]                          NaN   
3                                         NaN                          NaN   
4                                         NaN                          NaN   

                                            Based on  \
0                        [Characters, by Rex Weiner]   
1  [the novel, After Dark, My Sweet, by, Jim Thom...   
2             [Air America, by, Christopher Robbins]   
3                                                NaN   
4                                                NaN   

                                            Starring  ... Predecessor  \
0  [Andrew Dice Clay, Wayne Newton, Priscilla Pre...  ...         NaN   
1  [Jason Patric, Rachel Ward, Bruce Dern, George...  ...         NaN   
2  [Mel Gibson, Robert Downey Jr., Nancy Travis, ...  ...         NaN   
3  [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  ...         NaN   
4        [Paul Hogan, Elias Koteas, Linda Kozlowski]  ...         NaN   

  Founders Area served Products Services Russian Hebrew Revenue  \
0      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
1      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
2      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
3      NaN         NaN      NaN      NaN     NaN    NaN     NaN   
4      NaN         NaN      NaN      NaN     NaN    NaN     NaN   

  Operating income Polish  
0              NaN    NaN  
1              NaN    NaN  
2              NaN    NaN  
3              NaN    NaN  
4              NaN    NaN  

[5 rows x 193 columns]

In [7]:
wiki_movies_df.columns.to_list()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resti

In [8]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie]
len(wiki_movies)

7080

In [9]:
wiki_movies_df2 = pd.DataFrame(wiki_movies)
wiki_movies_df2.head()

url  year  \
0  https://en.wikipedia.org/wiki/The_Adventures_o...  1990   
1  https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990   
2   https://en.wikipedia.org/wiki/Air_America_(film)  1990   
3    https://en.wikipedia.org/wiki/Alice_(1990_film)  1990   
4      https://en.wikipedia.org/wiki/Almost_an_Angel  1990   

                               imdb_link                            title  \
0  https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane   
1  https://www.imdb.com/title/tt0098994/             After Dark, My Sweet   
2  https://www.imdb.com/title/tt0099005/                      Air America   
3  https://www.imdb.com/title/tt0099012/                            Alice   
4  https://www.imdb.com/title/tt0099018/                  Almost an Angel   

          Directed by                  Produced by  \
0        Renny Harlin   [Steve Perry, Joel Silver]   
1         James Foley  [Ric Kidney, Robert Redlin]   
2  Roger Spottiswoode               Daniel Melnick   
3         Woody Allen              Robert Greenhut   
4        John Cornell                 John Cornell   

                                Screenplay by                     Story by  \
0  [David Arnott, James Cappe, Daniel Waters]  [David Arnott, James Cappe]   
1                [James Foley, Robert Redlin]                          NaN   
2                  [John Eskow, Richard Rush]                          NaN   
3                                         NaN                          NaN   
4                                         NaN                          NaN   

                                            Based on  \
0                        [Characters, by Rex Weiner]   
1  [the novel, After Dark, My Sweet, by, Jim Thom...   
2             [Air America, by, Christopher Robbins]   
3                                                NaN   
4                                                NaN   

                                            Starring  ... Hepburn Literally  \
0  [Andrew Dice Clay, Wayne Newton, Priscilla Pre...  ...     NaN       NaN   
1  [Jason Patric, Rachel Ward, Bruce Dern, George...  ...     NaN       NaN   
2  [Mel Gibson, Robert Downey Jr., Nancy Travis, ...  ...     NaN       NaN   
3  [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  ...     NaN       NaN   
4        [Paul Hogan, Elias Koteas, Linda Kozlowski]  ...     NaN       NaN   

  Cantonese Chinese Yiddish Arabic Romanized Russian Hebrew Polish  
0       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
1       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
2       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
3       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
4       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  

[5 rows x 78 columns]

In [10]:
wiki_movies2 = [movie for movie in wiki_movies
               if 'No. of episodes' not in movie]

In [11]:
len(wiki_movies2)

7076

In [12]:
wiki_movies_df_2 = pd.DataFrame(wiki_movies2) #creating non destructive variables
wiki_movies_df_2.head()

url  year  \
0  https://en.wikipedia.org/wiki/The_Adventures_o...  1990   
1  https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990   
2   https://en.wikipedia.org/wiki/Air_America_(film)  1990   
3    https://en.wikipedia.org/wiki/Alice_(1990_film)  1990   
4      https://en.wikipedia.org/wiki/Almost_an_Angel  1990   

                               imdb_link                            title  \
0  https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane   
1  https://www.imdb.com/title/tt0098994/             After Dark, My Sweet   
2  https://www.imdb.com/title/tt0099005/                      Air America   
3  https://www.imdb.com/title/tt0099012/                            Alice   
4  https://www.imdb.com/title/tt0099018/                  Almost an Angel   

          Directed by                  Produced by  \
0        Renny Harlin   [Steve Perry, Joel Silver]   
1         James Foley  [Ric Kidney, Robert Redlin]   
2  Roger Spottiswoode               Daniel Melnick   
3         Woody Allen              Robert Greenhut   
4        John Cornell                 John Cornell   

                                Screenplay by                     Story by  \
0  [David Arnott, James Cappe, Daniel Waters]  [David Arnott, James Cappe]   
1                [James Foley, Robert Redlin]                          NaN   
2                  [John Eskow, Richard Rush]                          NaN   
3                                         NaN                          NaN   
4                                         NaN                          NaN   

                                            Based on  \
0                        [Characters, by Rex Weiner]   
1  [the novel, After Dark, My Sweet, by, Jim Thom...   
2             [Air America, by, Christopher Robbins]   
3                                                NaN   
4                                                NaN   

                                            Starring  ... Hepburn Literally  \
0  [Andrew Dice Clay, Wayne Newton, Priscilla Pre...  ...     NaN       NaN   
1  [Jason Patric, Rachel Ward, Bruce Dern, George...  ...     NaN       NaN   
2  [Mel Gibson, Robert Downey Jr., Nancy Travis, ...  ...     NaN       NaN   
3  [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  ...     NaN       NaN   
4        [Paul Hogan, Elias Koteas, Linda Kozlowski]  ...     NaN       NaN   

  Cantonese Chinese Yiddish Arabic Romanized Russian Hebrew Polish  
0       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
1       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
2       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
3       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  
4       NaN     NaN     NaN    NaN       NaN     NaN    NaN    NaN  

[5 rows x 75 columns]

### Take a look at the languages

If we take a look at the urls, we can see that the languages are for alternate titles of the movie in those languages. **We can combine all of them into one dictionary that has all the alternate titles** 

In [13]:
wiki_movies_df_2.Arabic.count()

2

In [14]:
wiki_movies_df_2[wiki_movies_df_2['Arabic'].notnull()] 

url  year  \
6834  https://en.wikipedia.org/wiki/The_Insult_(film)  2018   
7058   https://en.wikipedia.org/wiki/Capernaum_(film)  2018   

                                  imdb_link       title    Directed by  \
6834  https://www.imdb.com/title/tt7048622/  The Insult   Ziad Doueiri   
7058  https://www.imdb.com/title/tt8267604/   Capernaum  Nadine Labaki   

                                            Produced by  \
6834  [Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...   
7058                    [Michel Merkt, Khaled Mouzanar]   

                                          Screenplay by  \
6834                                                NaN   
7058  [Nadine Labaki, Jihad Hojaily, Michelle Keserw...   

                                               Story by Based on  \
6834                                                NaN      NaN   
7058  [Georges Khabbaz, Nadine Labaki, Michelle Kese...      NaN   

                                               Starring  ... Hepburn  \
6834                       [Adel Karam, Kamel El Basha]  ...     NaN   
7058  [Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...  ...     NaN   

        Literally Cantonese Chinese Yiddish       Arabic        Romanized  \
6834  Case No. 23       NaN     NaN     NaN  قضية رقم ٢٣  Qadiyya raqm 23   
7058          NaN       NaN     NaN     NaN    کفرناحوم‎              NaN   

     Russian Hebrew Polish  
6834     NaN    NaN    NaN  
7058     NaN    NaN    NaN  

[2 rows x 75 columns]

In [15]:
sorted(wiki_movies_df_2.columns.to_list()) # to sort columns in alphabetical order

['Adaptation by',
 'Also known as',
 'Animation by',
 'Arabic',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cantonese',
 'Chinese',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'French',
 'Genre',
 'Hangul',
 'Hebrew',
 'Hepburn',
 'Japanese',
 'Label',
 'Language',
 'Length',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Picture format',
 'Polish',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Simplifie

New fct

In [16]:
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles

    return movie


In [17]:
clean_movies = [clean_movie(movie) for movie in wiki_movies2]

In [18]:
wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Picture format',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [19]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7076 entries, 0 to 7075
Data columns (total 56 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   url                     7076 non-null   object
 1   year                    7076 non-null   int64 
 2   imdb_link               7076 non-null   object
 3   title                   7075 non-null   object
 4   Directed by             7074 non-null   object
 5   Produced by             6716 non-null   object
 6   Screenplay by           2318 non-null   object
 7   Story by                1002 non-null   object
 8   Based on                2190 non-null   object
 9   Starring                6892 non-null   object
 10  Narrated by             282 non-null    object
 11  Music by                6482 non-null   object
 12  Cinematography          6378 non-null   object
 13  Edited by               6379 non-null   object
 14  Productioncompany       4529 non-null   object
 15  Dist

There are 21 movies that have alternate titles

In [20]:
wiki_movies_df['alt_titles'].count()

21

In [21]:
wiki_movies_df[wiki_movies_df['alt_titles'].notnull()]

url  year  \
858   https://en.wikipedia.org/wiki/The_Wedding_Banquet  1993   
1342  https://en.wikipedia.org/wiki/Night_Watch_(199...  1995   
1534  https://en.wikipedia.org/wiki/East_Palace,_Wes...  1996   
1888    https://en.wikipedia.org/wiki/The_Fifth_Element  1997   
3413  https://en.wikipedia.org/wiki/Wonderful_Days_(...  2003   
4238           https://en.wikipedia.org/wiki/Shark_Bait  2006   
4790    https://en.wikipedia.org/wiki/Waltz_with_Bashir  2008   
6393  https://en.wikipedia.org/wiki/When_Marnie_Was_...  2015   
6456             https://en.wikipedia.org/wiki/Ip_Man_3  2016   
6613  https://en.wikipedia.org/wiki/The_Great_Wall_(...  2017   
6620             https://en.wikipedia.org/wiki/Rock_Dog  2017   
6661        https://en.wikipedia.org/wiki/Born_in_China  2017   
6719       https://en.wikipedia.org/wiki/Menashe_(film)  2017   
6829  https://en.wikipedia.org/wiki/Mary_and_the_Wit...  2018   
6834    https://en.wikipedia.org/wiki/The_Insult_(film)  2018   
6849      https://en.wikipedia.org/wiki/Loveless_(film)  2018   
6862  https://en.wikipedia.org/wiki/Foxtrot_(2017_film)  2018   
7009  https://en.wikipedia.org/wiki/My_Hero_Academia...  2018   
7054          https://en.wikipedia.org/wiki/Shoplifters  2018   
7058     https://en.wikipedia.org/wiki/Capernaum_(film)  2018   
7070  https://en.wikipedia.org/wiki/Cold_War_(2018_f...  2018   

                                  imdb_link  \
858   https://www.imdb.com/title/tt0107156/   
1342  https://www.imdb.com/title/tt0113984/   
1534  https://www.imdb.com/title/tt0119007/   
1888  https://www.imdb.com/title/tt0119116/   
3413  https://www.imdb.com/title/tt0353014/   
4238  https://www.imdb.com/title/tt0820142/   
4790  https://www.imdb.com/title/tt1185616/   
6393  https://www.imdb.com/title/tt3398268/   
6456  https://www.imdb.com/title/tt2888046/   
6613  https://www.imdb.com/title/tt2034800/   
6620  https://www.imdb.com/title/tt2822672/   
6661  https://www.imdb.com/title/tt4629266/   
6719  https://www.imdb.com/title/tt6333086/   
6829  https://www.imdb.com/title/tt6336356/   
6834  https://www.imdb.com/title/tt7048622/   
6849  https://www.imdb.com/title/tt6304162/   
6862  https://www.imdb.com/title/tt6896536/   
7009  https://www.imdb.com/title/tt7745068/   
7054  https://www.imdb.com/title/tt8075192/   
7058  https://www.imdb.com/title/tt8267604/   
7070  https://www.imdb.com/title/tt6543652/   

                                       title                      Directed by  \
858                      The Wedding Banquet                          Ang Lee   
1342                              Nightwatch                    David Jackson   
1534                East Palace, West Palace                       Zhang Yuan   
1888                       The Fifth Element                       Luc Besson   
3413                          Wonderful Days                   Kim Moon-saeng   
4238  Shark Bait (AKA: The Reef: Shark Bait)      [Howard E. Baker, John Fox]   
4790                       Waltz with Bashir                       Ari Folman   
6393                   When Marnie Was There             Hiromasa Yonebayashi   
6456                                Ip Man 3                       Wilson Yip   
6613                          The Great Wall                      Zhang Yimou   
6620                                Rock Dog                      Ash Brannon   
6661                           Born in China                         Lu Chuan   
6719                                 Menashe  [Joshua Z. Weinstein, [, yi, ]]   
6829             Mary and The Witch's Flower             Hiromasa Yonebayashi   
6834                              The Insult                     Ziad Doueiri   
6849                                Loveless               Andrey Zvyagintsev   
6862                                 Foxtrot                      Samuel Maoz   
7009            My Hero Academia: Two Heroes                   Kenji Nagasaki   
7054                             Shoplifters   

In [22]:
wiki_movies_df[wiki_movies_df['alt_titles'].notnull()]['alt_titles']

858            {'Mandarin': 'Xǐyàn', 'Traditional': '喜宴'}
1342       {'Also known as': 'Detonator II: Night Watch'}
1534    {'Mandarin': 'Dōng Gōng Xī Gōng', 'Simplified'...
1888                   {'French': 'Le Cinquième Élément'}
3413    {'Hangul': '원더풀 데이즈', 'McCune–Reischauer': 'Wŏ...
4238    {'Hangul': '파이 스토리', 'McCune–Reischauer': 'P‘a...
4790                  {'Original title': 'ואלס עם באשיר'}
6393    {'Hepburn': 'Omoide no Mānī', 'Japanese': '思い出...
6456    {'Cantonese': ['Jip', '6', 'Man', '6', 'Saam',...
6613    {'Mandarin': 'Cháng Chéng', 'Simplified': '长城'...
6620                                  {'Chinese': '摇滚藏獒'}
6661    {'Simplified': '我们诞生在中国', 'Traditional': '我們誕生...
6719                                  {'Yiddish': 'מנשה'}
6829    {'Hepburn': 'Meari to Majo no Hana', 'Japanese...
6834    {'Arabic': 'قضية رقم ٢٣', 'Literally': 'Case N...
6849     {'Romanized': 'Nelyubov', 'Russian': 'Нелюбовь'}
6862                           {'Hebrew': 'פוֹקְסטְרוֹט'}
7009    {'Hepb

# Cleaning function finished

Here we are adding the fct that cleans columns that serve the same purpose

In [23]:
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    # combine alternate titles into one list
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune-Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles

    # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release Date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')

    return movie

In [24]:
clean_movies = [clean_movie(movie) for movie in wiki_movies2]
wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())


['Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Created by',
 'Director',
 'Distributor',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'McCune–Reischauer',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Picture format',
 'Preceded by',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Recorded',
 'Release date',
 'Running time',
 'Starring',
 'Suggested by',
 'Venue',
 'Voices of',
 'Writer(s)',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [25]:
wiki_movies_df.info() # now there are only 40 columns after cleaning the names of the columns. Instead of 56

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7076 entries, 0 to 7075
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   url                     7076 non-null   object
 1   year                    7076 non-null   int64 
 2   imdb_link               7076 non-null   object
 3   title                   7075 non-null   object
 4   Based on                2190 non-null   object
 5   Starring                6892 non-null   object
 6   Narrated by             282 non-null    object
 7   Cinematography          6378 non-null   object
 8   Release date            7044 non-null   object
 9   Running time            6936 non-null   object
 10  Country                 6837 non-null   object
 11  Language                6832 non-null   object
 12  Budget                  4764 non-null   object
 13  Box office              5517 non-null   object
 14  Director                7076 non-null   object
 15  Dist

In [26]:
wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
wiki_movies_df.info() # we can see that we created a new column with the imdb id
# now we have 41 bc we created one more with the imdb id

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7076 entries, 0 to 7075
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   url                     7076 non-null   object
 1   year                    7076 non-null   int64 
 2   imdb_link               7076 non-null   object
 3   title                   7075 non-null   object
 4   Based on                2190 non-null   object
 5   Starring                6892 non-null   object
 6   Narrated by             282 non-null    object
 7   Cinematography          6378 non-null   object
 8   Release date            7044 non-null   object
 9   Running time            6936 non-null   object
 10  Country                 6837 non-null   object
 11  Language                6832 non-null   object
 12  Budget                  4764 non-null   object
 13  Box office              5517 non-null   object
 14  Director                7076 non-null   object
 15  Dist

In [27]:
len(wiki_movies_df)

7076

Now that the columns are tidied up, the last claning we are going to do to the data consists of removing duplicate rows. We can remove them now that we know the movie's id

In [28]:
wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
len(wiki_movies_df)

7033

There were 43 rows deleted after removing duplicates 

# Removing unecessary columns

Now that we've consolidated redundant columns, we want to see which columns don't contain much useful data. Since this is scraped data, it's possible many columns are mostly null.

In [29]:
[[column,wiki_movies_df[column].isnull().sum()] for column in wiki_movies_df.columns] 
# To count how many null values are in each column

[['url', 0],
 ['year', 0],
 ['imdb_link', 0],
 ['title', 1],
 ['Based on', 4852],
 ['Starring', 184],
 ['Narrated by', 6752],
 ['Cinematography', 691],
 ['Release date', 32],
 ['Running time', 139],
 ['Country', 236],
 ['Language', 244],
 ['Budget', 2295],
 ['Box office', 1548],
 ['Director', 0],
 ['Distributor', 357],
 ['Editor(s)', 548],
 ['Composer(s)', 518],
 ['Producer(s)', 202],
 ['Production company(s)', 1678],
 ['Writer(s)', 199],
 ['Genre', 6923],
 ['Original language(s)', 6875],
 ['Original network', 6908],
 ['Executive producer(s)', 6936],
 ['Production location(s)', 6986],
 ['Picture format', 6969],
 ['Audio format', 6972],
 ['Voices of', 7031],
 ['Followed by', 7024],
 ['Created by', 7023],
 ['Preceded by', 7023],
 ['Suggested by', 7032],
 ['alt_titles', 7012],
 ['Recorded', 7031],
 ['Venue', 7032],
 ['Label', 7031],
 ['Animation by', 7031],
 ['Color process', 7032],
 ['McCune–Reischauer', 7031],
 ['imdb_id', 0]]

In [30]:
wiki_movies_df.info() # to see the opposite: how many non-null values each column has

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   url                     7033 non-null   object
 1   year                    7033 non-null   int64 
 2   imdb_link               7033 non-null   object
 3   title                   7032 non-null   object
 4   Based on                2181 non-null   object
 5   Starring                6849 non-null   object
 6   Narrated by             281 non-null    object
 7   Cinematography          6342 non-null   object
 8   Release date            7001 non-null   object
 9   Running time            6894 non-null   object
 10  Country                 6797 non-null   object
 11  Language                6789 non-null   object
 12  Budget                  4738 non-null   object
 13  Box office              5485 non-null   object
 14  Director                7033 non-null   object
 15  Dist

### Creating a code that eliminates columns that have less than 90% null values 

In [31]:
wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]
wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]

In [32]:
wiki_movies_df.info() # we have cleaned the dataset to end up with 21 useful columns 
#instead of 191 messy ones at the beggining

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   url                    7033 non-null   object
 1   year                   7033 non-null   int64 
 2   imdb_link              7033 non-null   object
 3   title                  7032 non-null   object
 4   Based on               2181 non-null   object
 5   Starring               6849 non-null   object
 6   Cinematography         6342 non-null   object
 7   Release date           7001 non-null   object
 8   Running time           6894 non-null   object
 9   Country                6797 non-null   object
 10  Language               6789 non-null   object
 11  Budget                 4738 non-null   object
 12  Box office             5485 non-null   object
 13  Director               7033 non-null   object
 14  Distributor            6676 non-null   object
 15  Editor(s)            

- The box office column should be numeric
- The budget column should be numeric
- The released date should be a date object
- The running time should be numeric


In [33]:
wiki_movies_df['Box office'] #should be numeric

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...       
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
7075                 NaN
Name: Box office, Length: 7033, dtype: object

In [37]:
box_office = wiki_movies_df['Box office'].dropna()
box_office #now we have less data entries... just the ones with non-null values

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...       
7070       $19.4 million
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
Name: Box office, Length: 5485, dtype: object

As regex only work with strings we have to creade a line of code that checks which data entries are str and which not. 

In [38]:
def is_not_a_string(x):
    return type(x) != str

In [39]:
box_office[box_office.map(is_not_a_string)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...                  
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

In this case it would be better practice to use a lambda function. Remember, this is what lambda functions are made for. Instead of creating a new function with a block of code and the def keyword, we can create an anonymous lambda function right inside the map() call.

In [42]:
box_office[box_office.map(lambda x: type(x) != str)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...                  
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

We can see that there are some data points that were stored as lists. There might be some of them that are just numbers

In [44]:
box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)
box_office

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...       
7070       $19.4 million
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
Name: Box office, Length: 5485, dtype: object

There are some data points that are writen as 12.3 million/billion and others that have all the numbers like $4,000,000,000

In [45]:
import re #make sure to always include this imports at the beginning of the notebook

Regular expression we are going to use for box_office: 

In [48]:
form_one = r'\$\d+\.?\d*\s*[mb]illion'

In [49]:
box_office.str.contains(form_one, flags=re.IGNORECASE).sum()

3896

That means that from the 5,485 data points that box_office had only 3896 were in that format, we should think and expect the other ones are in the full number format $#,###,###,###

In [51]:
form_two = r'\$\d{1,3}(?:,\d{3})+' # NOTE: I missed the comma and it gave me that it found one value
box_office.str.contains(form_two, flags=re.IGNORECASE).sum()

1544

In [52]:
1544 + 3896

5440

In [57]:
5485 - 5440

45

Meaning there are still 45 data entries not being accounted for. To find them:

To make our code easier to understand, we'll create two Boolean Series called matches_form_one and matches_form_two, and then select the box office values that don't match either. First, create the two Boolean series with the following code:

In [53]:
matches_form_one = box_office.str.contains(form_one, flags=re.IGNORECASE)
matches_form_two = box_office.str.contains(form_two, flags=re.IGNORECASE)

In [54]:
# this will throw an error!
box_office[(not matches_form_one) and (not matches_form_two)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The code above will give you a ValueError with the explanation "The truth value of a Series is ambiguous." (Unfortunately, the meaning of that error is also ambiguous.)

Instead, Pandas has element-wise logical operators:

The element-wise negation operator is the tilde: ~ (similar to "not")
The element-wise logical "and" is the ampersand: &
The element-wise logical "or" is the pipe: |
The code we want to use is as follows:

In [56]:
box_office[~matches_form_one & ~matches_form_two].count() # We are saying the same thing that the error above

47

I dont get why 47 if we were only missing 45 values 

In [58]:
box_office[~matches_form_one & ~matches_form_two]

34                         US$ 4,212,828
79                              $335.000
110                   $4.35-4.37 million
130                        US$ 4,803,039
600                           $5000 (US)
731                         $ 11,146,270
957                             $ 50,004
1070                          35,254,617
1147    $ 407,618 (U.S.) (sub-total) [1]
1446                        $ 11,829,959
1480                          £3 million
1611                            $520.000
1865                        ¥1.1 billion
2032                                 N/A
2091                                $309
2130               US$ 171.8 million [9]
2257                   US$ 3,395,581 [1]
2263            $ 1,223,034 ( domestic )
2347                            $282.175
2638            $ 104,883 (US sub-total)
2665         926,423 admissions (France)
2697      $ 1.7 million (US) (sub-total)
2823                            $414.000
2924                            $621.000
3088           $

We can fix our pattern matches to capture more values by addressing these issues:

Some values have spaces in between the dollar sign and the number.
Some values use a period as a thousands separator, not a comma.
Some values are given as a range.
"Million" is sometimes misspelled as "millon."

- To fix the first one where some values have spaces in b/t the dollar sign and the number

In [59]:
form_one = r'\$\s*\d+\.?\d*\s*[mb]illion'
form_two = r'\$\s*\d{1,3}(?:,\d{3})+'

- Some values use a period as a thousands separator, not a comma.

In [60]:
form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+'

The results will also match values like 1.234 billion, but we're trying to change raw numbers like $123.456.789. We don't want to capture any values like 1.234 billion, so we need to add a negative lookahead group that looks ahead for "million" or "billion" after the number and rejects the match if it finds those strings. Don't forget the space! The new form should look like this:

In [61]:
form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'


- Some values are given as a range.

To solve this problem, we'll search for any string that starts with a dollar sign and ends with a hyphen, and then replace it with just a dollar sign using the replace() method. The first argument in the replace() method is the substring that will be replaced, and the second argument in the replace() method is the string to replace it with. We can use regular expressions in the first argument by sending the parameter regex=True, as shown below.

In [62]:
box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

- "Million" is sometimes misspelled as "millon."

In [63]:
form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'

# Changing datatypes taking into consideration all data entries' forms

In [ ]:
box_office.str.extract(f'({form_one}|{form_two})')

Now we need a function to turn the extracted values into a numeric value. We'll call it parse_dollars, and parse_dollars will take in a string and return a floating-point number. We'll start by making a skeleton function with comments explaining each step, and then fill in the steps with actual code.

Since we're working directly with strings, we'll use the re module to access the regular expression functions. We'll use re.match(pattern, string) to see if our string matches a pattern. To start, we'll make some small alterations to the forms we defined, splitting the million and billion matches from form one.

Next, we'll use `re.sub(pattern, replacement_string, string)` to remove dollar signs, spaces, commas, and letters, if necessary.

Finally, convert all the strings to floats, multiply by the right amount, and return the value.


In [64]:
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan

    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " million"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a million
        value = float(s) * 10**6

        # return value
        return value

    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " billion"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a billion
        value = float(s) * 10**9

        # return value
        return value

    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

        # remove dollar sign and commas
        s = re.sub('\$|,','', s)

        # convert to float
        value = float(s)

        # return value
        return value

    # otherwise, return NaN
    else:
        return np.nan

Now we have everything we need to parse the box office values to numeric values.

First, we need to extract the values from box_office using str.extract. Then we'll apply parse_dollars to the first column in the DataFrame returned by str.extract, which in code looks like the following:

In [65]:
wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)

In [69]:
wiki_movies_df.info() # we already created another column with the changed dtype values of box office

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   url                    7033 non-null   object 
 1   year                   7033 non-null   int64  
 2   imdb_link              7033 non-null   object 
 3   title                  7032 non-null   object 
 4   Based on               2181 non-null   object 
 5   Starring               6849 non-null   object 
 6   Cinematography         6342 non-null   object 
 7   Release date           7001 non-null   object 
 8   Running time           6894 non-null   object 
 9   Country                6797 non-null   object 
 10  Language               6789 non-null   object 
 11  Budget                 4738 non-null   object 
 12  Box office             5485 non-null   object 
 13  Director               7033 non-null   object 
 14  Distributor            6676 non-null   object 
 15  Edit

In [68]:
wiki_movies_df['box_office'], wiki_movies_df['Box office'] # the new table is a lot better so we can drop it

(0       21400000.0
 1        2700000.0
 2       57718089.0
 3        7331647.0
 4        6939946.0
            ...    
 7071    41900000.0
 7072    76100000.0
 7073    38400000.0
 7074     5500000.0
 7075           NaN
 Name: box_office, Length: 7033, dtype: float64,
 0          $21.4 million
 1           $2.7 million
 2            $57,718,089
 3             $7,331,647
 4       $6,939,946 (USA)
               ...       
 7071       $41.9 million
 7072       $76.1 million
 7073       $38.4 million
 7074        $5.5 million
 7075                 NaN
 Name: Box office, Length: 7033, dtype: object)

In [70]:
wiki_movies_df.drop('Box office', axis=1, inplace=True)

In [71]:
wiki_movies_df.info() # Check to see if dropped

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   url                    7033 non-null   object 
 1   year                   7033 non-null   int64  
 2   imdb_link              7033 non-null   object 
 3   title                  7032 non-null   object 
 4   Based on               2181 non-null   object 
 5   Starring               6849 non-null   object 
 6   Cinematography         6342 non-null   object 
 7   Release date           7001 non-null   object 
 8   Running time           6894 non-null   object 
 9   Country                6797 non-null   object 
 10  Language               6789 non-null   object 
 11  Budget                 4738 non-null   object 
 12  Director               7033 non-null   object 
 13  Distributor            6676 non-null   object 
 14  Editor(s)              6485 non-null   object 
 15  Comp

# Now we can go ahead and clean the budget column


In [74]:
budget = wiki_movies_df['Budget'].dropna()
budget

0        $20 million
1         $6 million
2        $35 million
3        $12 million
4        $25 million
            ...     
7070    €4.3 million
7071     $42 million
7072     $60 million
7073     $20 million
7074      $9 million
Name: Budget, Length: 4738, dtype: object

In [75]:
# convert listst into strings by join()

budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)


In [76]:
# Then remove any values between a dollar sign and a hyphen (for budgets given in ranges):

budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)


In [77]:
matches_form_one = budget.str.contains(form_one, flags=re.IGNORECASE)
matches_form_two = budget.str.contains(form_two, flags=re.IGNORECASE)
budget[~matches_form_one & ~matches_form_two]

136                         Unknown
204     60 million Norwegian Kroner
478                         Unknown
973             $34 [3] [4] million
1126               $120 [4] million
1226                        Unknown
1278                            HBO
1374                     £6,000,000
1397                     13 million
1480                   £2.8 million
1734                   CAD2,000,000
1913     PHP 85 million (estimated)
1948                    102,888,900
1953                   3,500,000 DM
1973                     ₤2,300,874
2281                     $14 milion
2451                     ₤6,350,000
3144                   € 40 million
3360               $150 [6] million
3418                        $218.32
3802                   £4.2 million
3906                            N/A
3959                    760,000 USD
4470                       19 crore
4641                    £17 million
5034              $$200 [4] million
5055           $155 [2] [3] million
5419                $40 [4] 

In [79]:
budget[~matches_form_one & ~matches_form_two].count()

38

This are all the values that were not in any of both forms that we had from the box office regexs. 38 values

We can also see that now we have citation reference errors (numbers in square brackets). To remove them we use: 


In [80]:
budget = budget.str.replace(r'\[\d+\]\s*', '')
budget[~matches_form_one & ~matches_form_two]

136                         Unknown
204     60 million Norwegian Kroner
478                         Unknown
973                     $34 million
1126                   $120 million
1226                        Unknown
1278                            HBO
1374                     £6,000,000
1397                     13 million
1480                   £2.8 million
1734                   CAD2,000,000
1913     PHP 85 million (estimated)
1948                    102,888,900
1953                   3,500,000 DM
1973                     ₤2,300,874
2281                     $14 milion
2451                     ₤6,350,000
3144                   € 40 million
3360                   $150 million
3418                        $218.32
3802                   £4.2 million
3906                            N/A
3959                    760,000 USD
4470                       19 crore
4641                    £17 million
5034                  $$200 million
5055                   $155 million
5419                    $40 

In [81]:
budget[~matches_form_one & ~matches_form_two].count()

38

Here we can decide that the best thing to do is to drop them. They don't represent even 1% of the whole data 

Parsing budget and creating a new column for it

In [82]:
wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)

We can drop the original Budget column now

In [83]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   url                    7033 non-null   object 
 1   year                   7033 non-null   int64  
 2   imdb_link              7033 non-null   object 
 3   title                  7032 non-null   object 
 4   Based on               2181 non-null   object 
 5   Starring               6849 non-null   object 
 6   Cinematography         6342 non-null   object 
 7   Release date           7001 non-null   object 
 8   Running time           6894 non-null   object 
 9   Country                6797 non-null   object 
 10  Language               6789 non-null   object 
 11  Budget                 4738 non-null   object 
 12  Director               7033 non-null   object 
 13  Distributor            6676 non-null   object 
 14  Editor(s)              6485 non-null   object 
 15  Comp

In [84]:
wiki_movies_df.drop('Budget', axis=1, inplace=True)

In [85]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   url                    7033 non-null   object 
 1   year                   7033 non-null   int64  
 2   imdb_link              7033 non-null   object 
 3   title                  7032 non-null   object 
 4   Based on               2181 non-null   object 
 5   Starring               6849 non-null   object 
 6   Cinematography         6342 non-null   object 
 7   Release date           7001 non-null   object 
 8   Running time           6894 non-null   object 
 9   Country                6797 non-null   object 
 10  Language               6789 non-null   object 
 11  Director               7033 non-null   object 
 12  Distributor            6676 non-null   object 
 13  Editor(s)              6485 non-null   object 
 14  Composer(s)            6515 non-null   object 
 15  Prod

# To parse the release date

In [87]:
release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
release_date #we made all the data entries already a single line of text

0                            July 11, 1990 ( 1990-07-11 )
1       May 17, 1990 ( 1990-05-17 ) (Cannes Film Marke...
2                          August 10, 1990 ( 1990-08-10 )
3                        December 25, 1990 ( 1990-12-25 )
4                                       December 19, 1990
                              ...                        
7071     December 25, 2018 ( 2018-12-25 ) (United States)
7072    December 11, 2018 ( 2018-12-11 ) ( Samuel Gold...
7073    November 8, 2018 ( 2018-11-08 ) ( AFI Fest ) D...
7074    August 31, 2018 ( 2018-08-31 ) ( Telluride ) D...
7075                      28 December 2018 ( 2018-12-28 )
Name: Release date, Length: 7001, dtype: object

The forms we'll be parsing are:

- Full month name, one- to two-digit day, four-digit year (i.e., January 1, 2000)
- Four-digit year, two-digit month, two-digit day, with any separator (i.e., 2000-01-01)
- Full month name, four-digit year (i.e., January 2000)
- Four-digit year

In [88]:
date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]\d,\s\d{4}'
date_form_two = r'\d{4}.[01]\d.[123]\d'
date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
date_form_four = r'\d{4}'

Then extract (make into a df) all the values that have those regex patterns

In [ ]:
#release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)


To convert it into a new column

In [90]:
wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)
wiki_movies_df['release_date']

0      1990-07-11
1      1990-05-17
2      1990-08-10
3      1990-12-25
4      1990-12-19
          ...    
7071   2018-12-25
7072   2018-12-11
7073   2018-01-01
7074   2018-08-31
7075   2018-12-01
Name: release_date, Length: 7033, dtype: datetime64[ns]

# Lastly, parse running time

In [92]:
running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)
running_time

0                                 102 minutes
1                                 114 minutes
2                                 113 minutes
3                                 106 minutes
4                                  95 minutes
                        ...                  
7071                               90 minutes
7072                              132 minutes
7073                              120 minutes
7074                              123 minutes
7075    Variable; 90 minutes for default path
Name: Running time, Length: 6894, dtype: object

To count how many data entries look like the format we see ### minutes. 6528 out of the 6894

In [93]:
running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE).sum()


6528

In [94]:
# the other 366 look like this
running_time[running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE) != True]


9                                                 102 min
26                                                 93 min
28                                                32 min.
34                                                101 min
35                                                 97 min
                              ...                        
6500       114 minutes [1] 120 minutes (extended edition)
6643                                             104 mins
6709    90 minutes (theatrical) [1] 91 minutes (unrate...
7057    108 minutes (Original cut) 98 minutes (UK cut)...
7075                Variable; 90 minutes for default path
Name: Running time, Length: 366, dtype: object

here we are looking for the values that start with numbers and just looking to see if the second word starts with m to maybe look for abbreviations or badly spelled words

In [95]:
# it is the majority. almost the total 6894 total non-null data entries of the column
running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE).sum()


6877

the remaining are like this: 

In [96]:
running_time[running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE) != True]


668                     UK:84 min (DVD version) US:86 min
727                         78-102 min (depending on cut)
840                       Varies (79 [3] –84 [1] minutes)
1347                                              25 : 03
1443    United States: 77 minutes Argentina: 94 minute...
1499                                            1hr 35min
1551                                               varies
1774                    Netherlands:96 min, Canada:95 min
1777                                       approx. 14 min
2273                                           1 h 43 min
2993                                               1h 48m
3925                                              4 hours
4425    US domestic version: 86 minutes Original versi...
4967    Theatrical cut: 97 minutes Unrated cut: 107 mi...
5424                    115 [1] /123 [2] /128 [3] minutes
5447                                    1 hour 32 minutes
7075                Variable; 90 minutes for default path
Name: Running 

With our new pattern, it's time to extract values. We only want to extract digits, and we want to allow for both possible patterns. Therefore, we'll add capture groups around the \d instances as well as add an alternating character. Our code will look like the following.

In [97]:
running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')
running_time_extract

0    1    2
0     NaN  NaN  102
1     NaN  NaN  114
2     NaN  NaN  113
3     NaN  NaN  106
4     NaN  NaN   95
...   ...  ...  ...
7071  NaN  NaN   90
7072  NaN  NaN  132
7073  NaN  NaN  120
7074  NaN  NaN  123
7075  NaN  NaN   90

[6894 rows x 3 columns]

Unfortunately, this new DataFrame is all strings, we'll need to convert them to numeric values. Because we may have captured empty strings, we'll use the to_numeric() method and set the errors argument to 'coerce'. Coercing the errors will turn the empty strings into Not a Number (NaN), then we can use fillna() to change all the NaNs to zeros.

In [98]:
running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)
running_time_extract 

0    1      2
0     0.0  0.0  102.0
1     0.0  0.0  114.0
2     0.0  0.0  113.0
3     0.0  0.0  106.0
4     0.0  0.0   95.0
...   ...  ...    ...
7071  0.0  0.0   90.0
7072  0.0  0.0  132.0
7073  0.0  0.0  120.0
7074  0.0  0.0  123.0
7075  0.0  0.0   90.0

[6894 rows x 3 columns]

In [99]:
wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)
wiki_movies_df['running_time']

0       102.0
1       114.0
2       113.0
3       106.0
4        95.0
        ...  
7071     90.0
7072    132.0
7073    120.0
7074    123.0
7075     90.0
Name: running_time, Length: 7033, dtype: float64

In [100]:
wiki_movies_df.drop('Running time', axis=1, inplace=True)


# The data has been cleaned

In [101]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   url                    7033 non-null   object        
 1   year                   7033 non-null   int64         
 2   imdb_link              7033 non-null   object        
 3   title                  7032 non-null   object        
 4   Based on               2181 non-null   object        
 5   Starring               6849 non-null   object        
 6   Cinematography         6342 non-null   object        
 7   Release date           7001 non-null   object        
 8   Country                6797 non-null   object        
 9   Language               6789 non-null   object        
 10  Director               7033 non-null   object        
 11  Distributor            6676 non-null   object        
 12  Editor(s)              6485 non-null   object        
 13  Com

In [102]:
wiki_movies_df.head()

url  year  \
0  https://en.wikipedia.org/wiki/The_Adventures_o...  1990   
1  https://en.wikipedia.org/wiki/After_Dark,_My_S...  1990   
2   https://en.wikipedia.org/wiki/Air_America_(film)  1990   
3    https://en.wikipedia.org/wiki/Alice_(1990_film)  1990   
4      https://en.wikipedia.org/wiki/Almost_an_Angel  1990   

                               imdb_link                            title  \
0  https://www.imdb.com/title/tt0098987/  The Adventures of Ford Fairlane   
1  https://www.imdb.com/title/tt0098994/             After Dark, My Sweet   
2  https://www.imdb.com/title/tt0099005/                      Air America   
3  https://www.imdb.com/title/tt0099012/                            Alice   
4  https://www.imdb.com/title/tt0099018/                  Almost an Angel   

                                            Based on  \
0                        [Characters, by Rex Weiner]   
1  [the novel, After Dark, My Sweet, by, Jim Thom...   
2             [Air America, by, Christopher Robbins]   
3                                                NaN   
4                                                NaN   

                                            Starring  Cinematography  \
0  [Andrew Dice Clay, Wayne Newton, Priscilla Pre...     Oliver Wood   
1  [Jason Patric, Rachel Ward, Bruce Dern, George...    Mark Plummer   
2  [Mel Gibson, Robert Downey Jr., Nancy Travis, ...   Roger Deakins   
3  [Alec Baldwin, Blythe Danner, Judy Davis, Mia ...  Carlo Di Palma   
4        [Paul Hogan, Elias Koteas, Linda Kozlowski]    Russell Boyd   

                                        Release date        Country  \
0                  [July 11, 1990, (, 1990-07-11, )]  United States   
1  [May 17, 1990, (, 1990-05-17, ), (Cannes Film ...  United States   
2                [August 10, 1990, (, 1990-08-10, )]  United States   
3              [December 25, 1990, (, 1990-12-25, )]  United States   
4                                  December 19, 1990             US   

         Language  ...                       Editor(s)  \
0         English  ...                 Michael Tronick   
1         English  ...                 Howard E. Smith   
2  [English, Lao]  ...  [John Bloom, Lois Freeman-Fox]   
3         English  ...                  Susan E. Morse   
4         English  ...                    David Stiven   

               Composer(s)                  Producer(s)  \
0  [Cliff Eidelman, Yello]   [Steve Perry, Joel Silver]   
1            Maurice Jarre  [Ric Kidney, Robert Redlin]   
2            Charles Gross               Daniel Melnick   
3                      NaN              Robert Greenhut   
4            Maurice Jarre                 John Cornell   

                   Production company(s)                     Writer(s)  \
0                        Silver Pictures   [David Arnott, James Cappe]   
1                        Avenue Pictures  [James Foley, Robert Redlin]   
2  [Carolco Pictures, IndieProd Company]    [John Eskow, Richard Rush]   
3                                    NaN                   Woody Allen   
4                                    NaN                    Paul Hogan   

     imdb_id  box_office      budget  release_date  running_time  
0  tt0098987  21400000.0  20000000.0    1990-07-11         102.0  
1  tt0098994   2700000.0   6000000.0    1990-05-17         114.0  
2  tt0099005  57718089.0  35000000.0    1990-08-10         113.0  
3  tt0099012   7331647.0  12000000.0    1990-12-25         106.0  
4  tt0099018   6939946.0  25000000.0    1990-12-19          95.0  

[5 rows x 22 columns]

In [103]:
# To export it
wiki_movies_df.to_csv('Clean_Wiki_Movies.csv', index_label='Movie_ID')